name: Build

on: push
#on:
#  push:
#    tags:
#      - 'v*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo ${{matrix.TARGET}}
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: tauri build
      - uses: actions/upload-artifact@v2
        with:
          name: jsoneditor-${{matrix.TARGET}}
          path: src-tauri/target/release/
